### PR TITLE
Extend CI steps, gradle update, other small updates

### PR DESCRIPTION
**Pull request by dbast**
While getting more familiar with the toolchain, I put together some commands from the documentation into a script called `.ci.sh`, which this way serve as extended CI steps with the characteristics of integration/end2end tests. It also checks that the .gitignore is complete and shows if there are some dependency updates. The script runs via CI and locally (no copying of many commands from `.travis.yml` to reproduce locally).

The PR also updates the init.gradle, the gradle wrapper and the gradle versions plugin. Shellcheck for shell scripts is introduced and the findings are resolved.

This is done in preparation of updating all the plugins, dependencies and submodules to newer versions while testing that they play well together.

### All Submissions:

* [ ] Does your PR affect the documentation?
* [ ] If yes, did you update the documentation or create an issue for updating it?

The source of the documentation can be found in `/src/docs/manual`. 
To "publish" it, execute `./gradlew && ./copyDocs.sh`.
This will convert the `.adoc` file to HTML and copy them to the right folder so that github pages will pick them up.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Your first submission

* [ ] Welcome to the list of contributors! If you have any questions, feel free to ask them by creating a new issue
* [ ] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?

### New Feature Submissions:

1. [ ] Did you create new tests for your submission?
2. [ ] Does your submission pass all tests? (see travis check)

### Changes to Core Features:

* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Change to Documentation:

* [ ] Did you build the docs and copy them to the `/docs` folder?
* [ ] If not, did you create an issue for doing so?

inspiration: https://github.com/stevemao/github-issue-templates

### CODE REVIEW

**Comment by rdmueller** [comment]
so, the tests fail, because of my merge... I guess I will have to check this first...

**Comment by dbast** [comment]
hm. `./gradlew test --info` fails, which also seems to fail on master.

**Comment by rdmueller** [comment]
yes, I did a mistake and merged a PR which causes this problem. has to do with the fontsDir for PDFs
I already try to fix this.

**Comment by rdmueller** [comment]
now the test runs fine again.
Thanx for the PR!

**Pull request merged**
