### PR TITLE
test (dtcw): provide minimal automated test suite for dtcw

### LINKED ISSUE #988: Enable testing of dtcw
As a developer and maintainer of dtcw I would like to get a test suite which allows to prove the functionality of `dtcw` under certain conditions, e.g.,

- Tools to download/install/run DTC are available/not available, i.e., `curl` (or `wget`), JDK, ...
- Several ways to run DTC (sdk, local, docker).

**Additional context**
When changing the wrapper I would like to run some local tests but at latest the CI server (GH Actions) should make sure that no regression occurs.

### PR DESCRIPTION
**Pull request by mh182**
Here is a minimal example how I think we could provide a test suite for `dtcw`.

Detailed information about the test suite may be found in `test/README.adoc`.

What I would like to discuss is:
- Should we include this test suite as it is, which adds a development dependency to `bats-core` docker container?
- Location of test cases in `${project_root}/test`: I put it there since `dtcw` is located in the project root and not part of `docToolchain`
- Integration in the CI pipeline: when should we run the tests?
    - Required to be run before releasing `dtcw`
    - Note: the runtime of those tests may be quite long. 
    - Please note that long-running tests may be filtered

### CODE REVIEW

**Comment by mh182** [comment]
I would like to integrate the test suite. The test suite is not integrated in any CI build yet, which is fine.
The goal of this PR is to provide a test safety net for further refactoring.
The `dtcw` code can really need some more love ;-)

I added `SPDX-License-Identifier` and copyright information in the files I changed. We really should make sure to add this information in the files if possible. Maybe another issue we should add.

Please *do not* suqash merge this PR. The first change in `dtcw` was just a code reformat with no functional changes.
Otheriwse it is going to get hard to track what we changed.

**Review by rdmueller — APPROVED** [review]
looks good to me. thanx.

**Comment by rdmueller** [comment]
Great! We have tests :-)

So, this is ready to be merged?

"Merge pull request" or "Rebase and Merge"?

**Comment by rdmueller** [comment]
great! these tests even run in gitpod.io .
And you already created an extensive set of tests. wow!

**Comment by mh182** [comment]
As far as I can see, those tests do not cover the following areas:
- Operating systems I don't have access to:
    - macOS related stuff (Darwin)
    - Installation on MS Windows with `cygwin`
    - Installation on MS Windows on WSL
- developer related features like using `DTC_VERSION=latest` in combination with working in the git repository
- tasks which have some code, but I never used/tested:
    - `bakePreview`
    - `generateDeck`
- Running in headless mode

Do you have means to run those tests in a different environment?

> So, this is ready to be merged?

Yes. It is a starting point. We may add the other tests when we find bugs during development or someone reports one.

> "Merge pull request" or "Rebase and Merge"?

Rebase and merge.

**Comment by rdmueller** [comment]
cygwin: I would say it is unsupported. There is no reason to use cygwin.

WSL is a linux, so it is mostly supported by the tests

I'll merge now. Thanx for the contribution of these great features!

**Pull request merged**
