### PR TITLE
Release 3.4.1

### PR DESCRIPTION
**Pull request by PacoVK**
3.4.1 preparation 

### All Submissions:

* [x] Did you update the `changelog.adoc`?

### CODE REVIEW

**Review by rdmueller — APPROVED** [review]
LGTM

**Comment by PeterStange** [comment]
Hello Paco, Hello Ralf,

thanks for the new release. One short question: how does the dtcw is getting updated that is published for initial download (e.g. curl -Lo dtcw https://doctoolchain.org/dtcw)?

**Comment by rdmueller** [comment]
Hi Peter,

what exactly do you mean? Do you ask because dtcw still references the 3.4.0? We normally  increase the version within dtcw manually a few days/weeks to test the new version before we release the new dtcw file.

We then have a github action to trigger the release. 

https://doctoolchain.org/docToolchain/v2.0.x/025_development/030_create_new_release.html#_doctoolchain_wrapper_dtcw

Where you able to verify the new build?

**Comment by PeterStange** [comment]
> Hi Peter,
> 
> what exactly do you mean? Do you ask because dtcw still references the 3.4.0? 
Yes, my question was about the process to release the new dtcw file. 

> Where you able to verify the new build?
Yes, thank you. I was able to verify the release 3.4.1. No further problems observed until now.

**Comment by rdmueller** [comment]
ok. updated dtcw.

**Pull request merged**
