### PR TITLE
remove Java 21 from build

### PR DESCRIPTION
**Pull request by PacoVK**
We cannot support Java 21 as of now. See #1419

### CODE REVIEW

**Comment by rdmueller** [comment]
hm. shall we remove it or let it stay to remind us?

**Comment by PacoVK** [comment]
i am not sure how fast we can make it to 21 because there may be heavy rewrites to get rid of some dependencies that block us (remind, we could upgrade to 8 only through workaround for same reason and i fear this time it gets even harder) 
So i would vote to remove it, because red CI steps cause noice and emails for the sake of reminding that we are not able to upgrade :D An issue would be the better choice i guess

**Review by rdmueller — APPROVED** [review]
ok

**Comment by rdmueller** [comment]
ok. btw: I already suceeded with a basic replacement of jbake. For the next version, I want to workaround gradle

**Pull request merged**
