### PR TITLE
#762 added ability to use bearer authentication

### PR DESCRIPTION
**Pull request by z0lberg**
### All Submissions:

* [ ] Did you update the `changelog.adoc`?
* [ ] Does your PR affect the documentation?
* [ ] If yes, did you update the documentation or create an issue for updating it?

The source of the documentation can be found in `/src/docs/`.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Your first submission

* [ ] Welcome to the list of contributors! If you have any questions, feel free to ask them by creating a new issue
* [ ] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?

inspiration: https://github.com/stevemao/github-issue-templates

### CODE REVIEW

**Comment by rdmueller** [comment]
thanx for this PR. I think it will make sense to use this change to brush up the code a bit.

let's move those four parts where the headers are set into one function.
I will do so, as soon as I find some time

**Comment by z0lberg** [comment]
Hi! I moved code duplicates to one function.

**Comment by rdmueller** [comment]
great! This helps me a lot :-)
Thanx for your contribution!

**Comment by sideisra** [comment]
Hello @rdmueller,

is there a due date for the next release? I need this feature to move on with using doctoolchain.

Denny

**Comment by rdmueller** [comment]
then I will create a new release for you. I think we already collected some changes in the changelog. I put it on my todo list for tomorrow.

**Comment by z0lberg** [comment]
> Hello @rdmueller,
> 
> is there a due date for the next release? I need this feature to move on with using doctoolchain.
> 
> Denny

Hi! You can try my image with this changes included. https://hub.docker.com/r/bilart/bt_dooctoolchain

**Comment by rdmueller** [comment]
@sideisra sorry for the delays. I ran into some problems with the docker image. Couldn't install pygments :-(

but v2.0.4 is out now. Give it a try by modifying the version number in you `dtcw` file.

**Comment by rdmueller** [comment]
@z0lberg is your dockerfile somewhere available? I would like to sync yours and mine.

**Comment by z0lberg** [comment]
> @z0lberg is your dockerfile somewhere available? I would like to sync yours and mine.

here: https://hub.docker.com/r/bilart/bt_dooctoolchain

**Comment by rdmueller** [comment]
@z0lberg sorry, I am not so familiar with the dockerhub interface and can't find the dockerfile, only the image...

**Comment by z0lberg** [comment]
[Dockerfile.txt](https://github.com/docToolchain/docToolchain/files/8222567/Dockerfile.txt)

**Comment by rdmueller** [comment]
thanx! this helped me to re-add pygments

**Pull request merged**
