### PR TITLE
CI: Fix problem in ci-script

### PR DESCRIPTION
**Pull request by Rosi2143**
Signed-off-by: Schrotti <Schrott.Micha@web.de>

### All Submissions:

* [y] Did you update the `changelog.adoc`?
* [n] Does your PR affect the documentation?

### CODE REVIEW

**Comment by rdmueller** [comment]
thanx. is this part of the script still in use? I thought it was ok to comment it out since it only runs on the old branches.

**Comment by Rosi2143** [comment]
I don't know, but my #756 failed due to this missing change in .cl.sh.

We can remove the "else" branch completely. I just wasn't sure.

**Comment by rdmueller** [comment]
yes, I think we can remove it.

**Comment by rdmueller** [comment]
btw: I still ahve the problem that this script is triggered from PRs an fails...

**Pull request merged**
