### PR TITLE
1073 dtcw ci build

### LINKED ISSUE #543: dtcw: improve (on mac) - ng used for testing
## Is your feature request related to a problem? Please describe.
I downloaded dtcw into the /Downloads folder on mac, executed from there. Not sure if the path topics below could be avoided, if the wrapper would be put somewhere else?

1. The current beta docToolchain wrapper (dtcw) installable via doctoolchain.github.io/dtcw is using wget to download artifacts. Wget is not available as a standard tool on mac. 
```
./dtcw local
dtcw - docToolchain wrapper V0.11
force use of local install
docToolchain not installed.
doctoolchain not found
Do you wish to install doctoolchain to /Users/myuser/.doctoolchain?
1) Yes
2) No
#? 1
installing doctoolchain
./dtcw: line 120: wget: command not found
unzip:  cannot find or open /Users/myuser/.doctoolchain/source.zip, /Users/myuser/.doctoolchain/source.zip.zip or 
/Users/myuser/.doctoolchain/source.zip.ZIP.
bash: /Users/myuser/.doctoolchain/docToolchain-ng/bin/doctoolchain: No such file or directory
```
   To work around it, i did a brew install wget, to continue the tests.

2. The second line seems kind of duplicate? I cannot quite make out the intention behind it.
````
docToolchain not installed.
doctoolchain not found
````

3. If docker is chosen, but not available i would expect the script to stop when docker is not found, but it seems it does a local install instead, which has some errors:
[dtcw docker after brew wget.pdf](https://github.com/docToolchain/docToolchain/files/6032109/dtcw.docker.after.brew.wget.pdf)

**UPDATE:** In a second run the question for y/n did not occur as in the pdf, but a similar error:
```
* What went wrong:
Execution failed for task ':exportChangeLog'.
> java.io.IOException: Cannot run program "git" (in directory "/Users/jlo2k/Downloads/src/docs"): error=2, No such file or directory
```

4. After that i tried sdkman (without cleaning the previous) and got this, but expected as found somewhere in the code how to install sdkman instead of running into the gradle task:
```
./dtcw sdkman
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
FAILURE: Build failed with an exception.
* What went wrong:
Task 'sdkman' not found in root project 'docToolchain'.
* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 6s
```

Then i realized i should have used sdk not sdkman ... but works as expected, i might not be the only one who will do this mistake, maybe better catch it... but also cleaned all docToolchain folder before this run... so it might acually be an inconsistent result.

```
./dtcw sdk   
dtcw - docToolchain wrapper V0.11
force use of sdkman
docToolchain not installed.
please use sdkman to install docToolchain
$ sdk install doctoolchain ng-beta
```

5. Why is ng Gradle 6.6.1 instead of current master 6.7.1?

6. Finally i tried local install, but got a similar error like the previous installs with docker:
```
> Task :exportChangeLog FAILED
FAILURE: Build failed with an exception.
* Where:
Script '/Users/jlo2k/.doctoolchain/docToolchain-ng/scripts/exportChangelog.gradle' line: 15
* What went wrong:
Execution failed for task ':exportChangeLog'.
> java.io.IOException: Cannot run program "git" (in directory "/Users/myuser/Downloads/src/docs"): error=2, No such file or directory
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 57s
1 actionable task: 1 executed
```
7. Hoping that the other installation tasks succeeded i tried to download the DE template:
```
./dtcw downloadTemplate
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :downloadTemplate
Install arc42 documentation template.
For more information about arc42 see https://arc42.org
[ant:input] Which language do you want to install? (EN, DE, ES, RU)
<-<-------------> 0% EXECUTING [15s]
[ant:input] Do you want the template with or without help? (withhelp, plain)
<--<-<-------------> 0% EXECUTING [25s]
Download https://github.com/arc42/arc42-template/raw/master/dist/arc42-template-DE-plain-asciidoc.zip
arc42 template unpacked into /Users/myuser/Downloads/src/docs/arc42
added template to docToolchainConfig.groovy
use 'generateHTML' or 'generatePDF' to convert the template

BUILD SUCCESSFUL in 28s
```
8. Then i tried to create a pdf:
```
./dtcw generatePDF
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
arc42/arc42.adoc

> Task :generatePDF
Converting /Users/myuser/Downloads/src/docs/arc42/arc42.adoc
could not locate or load the pdf theme `custom in /Users/myuser/Downloads/pdfTheme; reverting to default theme

BUILD SUCCESSFUL in 32s
1 actionable task: 1 executed
```
I found that there really was not PDFTheme folder, so i copied it from the template folder and ran again:
```
./dtcw generatePDF
dtcw - docToolchain wrapper V0.11
home folder exists
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.6.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
arc42/arc42.adoc

> Task :generatePDF
Converting /Users/myuser/Downloads/src/docs/arc42/arc42.adoc

BUILD SUCCESSFUL in 19s
1 actionable task: 1 executed
```
The theme was still not applied, so i deleted the file and ran again. This time the pdf was created using the theme. As the doctoolchain_demo.adoc was not there i think a task misses the copy of the template folder. But when using the arc42 template, to have that demo file there is acutally distracting and confusing.

## Describe the solution you'd like
For 1.  verify if curl can be used for all intended platforms, e.g. sdkman and homebrew both do use it.
In general i presume the other errors are ng related, which eventually become fixed.

I wonder if a wrapper has some intelligence build in, if it would be worthwile to build in more automation:
Check what you find: local, docker, sdkman if only one is found leverage that instead of asking what to do. When a force of either is chosen, do not present text but acually ask if it should be installed first or maybe even go for it as it was already chosen. 

If the wrapper is incidentaly started in /Downloads /Documents /User (other typical non project folders) maybe ask wether it is really intended to run here.

## Describe alternatives you've considered
For 1. There is an alternative to create a mac specific workaround: an alias redirecting wget on mac to curl. See [Stackoverflow - OS X: equivalent of Linux's wget](https://stackoverflow.com/questions/4572153/os-x-equivalent-of-linuxs-wget)

## Additional context
N/A

### LINKED ISSUE #1073: Integrate dtcw tests into CI build
the new tests for the wrapper really help a lot!

Can we setup a test which downloads the current wrapper from https://doctoolchain.org/dtcw to test the correct deployment of it?

Would this make sense?

### PR DESCRIPTION
**Pull request by mh182**
Adds a new GHA workflow `dtcw-tests` which is only run when something in `dtcw` (or the tests) changes. 
Tests also the `dtcw` for macOS.

What we are missing now is running tests on MS Windows in the powershell.
Should we do that in this PR or make a separate ticket?

### CODE REVIEW

**Comment by rdmueller** [comment]
> What we are missing now is running tests on MS Windows in the powershell.
> Should we do that in this PR or make a separate ticket?

separate ticket. And powershell now also works on linux.

**Review by rdmueller — APPROVED** [review]

**Review by rdmueller — APPROVED** [review]

**Comment by mh182** [comment]
> > What we are missing now is running tests on MS Windows in the powershell.
> > Should we do that in this PR or make a separate ticket?
> 
> separate ticket. And powershell now also works on linux.

Really? I can't wait to see this in actions

**Comment by rdmueller** [comment]
can we switch the shell for the bats-tests?

Now that the dtcw.ps1 also runs on linux, we could switch the shell to `pwsh` and rename the `./dtcw` to `./dtcw-hide`. This way, the command `./dtcw` will execute `./dtcw.ps1` if run in powershell...

**Comment by mh182** [comment]
> can we switch the shell for the bats-tests?
> 
Not really. `bats` uses sub-shells (bash) for each test. I would be surprised if this would work.
I will take a look into it, but I'm not really confident.

IMHO the best approach would be to expand the existing test cases for the Powershell and run that in the CI build.

**Comment by rdmueller** [comment]
Ok. Lets use the spock tests

**Pull request merged**
