### PR TITLE
Move reveal.js and asciidoctor-reveal.js to submodules

### PR DESCRIPTION
**Pull request by jakubjab**
First part of #91, making reveal.js and asciidoctor-reveal.js submodules.
I have kept exactly the same versions as before, leaving upgrading out of this change.
The size of the repository is decreased from 13M to 7.2M.
The installation manual has become somehow more complicated, any suggestions are welcome. For example we could make init.sh script that would download all dependencies and move them to correct places.

### CODE REVIEW

**Comment by jakubjab** [comment]
Thinking about it some more, we could also use something like https://github.com/craigburke/client-dependencies-gradle, so that Gradle would automatically download dependencies using bower.

**Comment by rdmueller** [comment]
regarding bower: I would like to keep the dependencies low in order to get it easily up and running in a very restricted environment. So I prefere the submodule...

**Comment by rdmueller** [comment]
maybe we could add the bower variant as an option?

**Comment by rdmueller** [comment]
thanx for th PR and for updating the docs!

**Pull request merged**
