### PR TITLE
Fix issue #15 - change of character case in headline of Confluence

### PR DESCRIPTION
**Pull request by jakubjab**
publishToConfluence task is now searching for all pages within the space matching fuzzily the expected title. Then the page with the title matching the expected one is chosen in case-insensitive way. Pages with similar but different titles are not affected, even if matched by fuzzy search from Confluence.

### CODE REVIEW

**Comment by jakubjab** [comment]
@rdmueller - any comments on that?

**Comment by rdmueller** [comment]
sorry and thanx for the reminder! Will take a look at it this morning...

**Comment by rdmueller** [comment]
nice code. As I do understand, it does a fuzzy search and looks in the result for the page which matches the original page case insensitive. Great!
Please see my comment and decide if we want to shorten the code...

**Comment by rdmueller** [comment]
strange. You should be able to see it on this page...:

I guess this method can be replaced by

`def page = pages.find { page -> p.title.equalsIgnoreCase(realPageTitle) }`

and if it can be turned into a one-liner, I guess it can be written inline.

What do you think?

**Comment by rdmueller** [comment]
cool. thanx.
are you registered at https://hacktoberfest.digitalocean.com/ ?

**Pull request merged**
