### PR TITLE
Improve publish to confluence 

### PR DESCRIPTION
**Pull request by PacoVK**
related to #1186  embedded images are quite flaky to handle, there are too many moving parts. 
Hence, we must document the constraints when enabling `failOnMissingImages` and the default should just ignore missing images. 

This PR also adds several unit tests for `publishToConfluence` task.

**New features:**
* Confluence Editor is configurable (default: v1)

**Fixes**
* Page hash is always invisible in read mode
* Pages with new Editor are fullwidth again [reference](https://community.developer.atlassian.com/t/how-to-set-fixed-width-when-creating-new-page-with-rest-call/53591/13)

### CODE REVIEW

**Comment by PacoVK** [comment]
Test setup keeps in line with the propsal of #1178 @mh182

**Comment by PacoVK** [comment]
closes #1053

**Review by rdmueller — APPROVED** [review]
LGTM! Thanx - this is an important change!

**Comment by rdmueller** [comment]
we could add a changelog entry, couldn't we?

**Comment by rdmueller** [comment]
mh. all builds start to fail. there seems to be a problem with maven. Old version of libraries seem to be missing.

**Comment by PacoVK** [comment]
I guess it more an error on a mirror because it is available on mvncentral eg. https://mvnrepository.com/artifact/com.burgstaller/okhttp-digest/1.10 I hope i magically disappears soon, that we can proceed to integrate :D

**Pull request merged**
