### PR TITLE
master 2 ng

### PR DESCRIPTION
**Pull request by Hellmy**
### All Submissions:

* [x] Did you update the `changelog.adoc`?
* [ ] Does your PR affect the documentation?
* [ ] If yes, did you update the documentation or create an issue for updating it?

I've tried to cherry pick the relevant commits

### CODE REVIEW

**Comment by Hellmy** [comment]
@rdmueller any timeline for the pending pull requests?

**Comment by rdmueller** [comment]
thanx for the ping. I will try to merge this evening.

**Comment by Hellmy** [comment]
@rdmueller any chance to get this merged if I resolve the conflicts?

**Comment by jmini** [comment]
@Hellmy I did not follow all the details in this PR, but I am interested in the changes introduced to solve issue https://github.com/docToolchain/docToolchain/issues/612 (which is also part of this PR).

I created a new PR targeting the `ng` branch that contains only this change: https://github.com/docToolchain/docToolchain/pull/886
(and a little bit more, since tasks like `generateSite` was not present in the `master` branch at that time)

**Comment by rdmueller** [comment]
sorry, I really lack time to work on this project :-o

I just fixed the merge conflicts and will now see if this can be merged...

**Comment by rdmueller** [comment]
? 25 comits but no changes? Did we already merge these changes?
@Hellmy ?

**Comment by Hellmy** [comment]
Seems like other pull requests did the job, just reject this 

Am 2. August 2022 22:02:45 MESZ schrieb "Ralf D. Müller" ***@***.***>:
>? 25 comits but no changes? Did we already merge these changes?
***@***.*** ?

**Pull request closed without merging**
