### PR TITLE
Pull all Confluence page metadata from the selected space, to perform title match in-memory, and avoid CQL #352

### PR DESCRIPTION
**Pull request by LuisMuniz**
### All Submissions:

* [x] Does your PR affect the documentation?
* [x] If yes, did you update the documentation or create an issue for updating it?

### Your first submission

* [x] Have you added your name to the list of [contributors.adoc]

### New Feature Submissions:

1. [ ] Did you create new tests for your submission?
2. [x] Does your submission pass all tests? (see travis check)

### Changes to Core Features:

* [ ] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
Both on Confluence cloud and Server

### Change to Documentation:

* [x] Did you build the docs and copy them to the `/docs` folder?

### CODE REVIEW

**Comment by LuisMuniz** [comment]
related to #352

**Comment by rdmueller** [comment]
very cool PR! Let me think a bit about how I can test it...

**Comment by LuisMuniz** [comment]
Thanks!!

**Comment by rdmueller** [comment]
It seems that I don't find the time to test this PR, so I will merge it without testing.
Thanx for the effort you have put into it. I think this PR will make the confluence task much more stable!

**Comment by LuisMuniz** [comment]
I have tested it both with our (old) cloud account and with our new server account. I feel a bit guilty for not providing a unit test, but i have no idea how to set up a confluence instance via docker for CI. I think they don really support that use case.

**Comment by rdmueller** [comment]
no, don't feel guilty :-)
I am very glad that you added so much to this project!
THANX!

**Comment by LuisMuniz** [comment]
just putting my money where my mouth is, thanks to you and all other contributors.

**Pull request merged**
