### PR TITLE
Fix broken links and typos

### PR DESCRIPTION
**Pull request by jmini**
### All Submissions:

* [ ] Did you update the `changelog.adoc`?
* [x] Does your PR affect the documentation?
* [ ] If yes, did you update the documentation or create an issue for updating it?

The source of the documentation can be found in `/src/docs/`.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Your first submission

* [x] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?

### CODE REVIEW

**Comment by jmini** [comment]
I have run an html checker to see what was broken in the output of `generateSite`.

No Netlify preview link in this PR?

**Comment by rdmueller** [comment]
the netlify preview resulted from a test. So I removed it. Should I reactivate it? ok!

**Comment by rdmueller** [comment]
re-activated netlify. But I guess we can merge this even without preview...

**Comment by jmini** [comment]
> the netlify preview resulted from a test. So I removed it. Should I reactivate it? ok!

Up to you, but last time I clicked on the link to verify my change.

**Comment by rdmueller** [comment]
https://dtc-docs-preview.netlify.app/

**Pull request merged**
