### PR TITLE
#104 exportVisio

### PR DESCRIPTION
**Pull request by rdmueller**
new build tasks which exports Visio diagrams - thanx to Frank Pohl

### CODE REVIEW

**Comment by rdmueller** [comment]
Since this is a new task, it will not break anything, but regarding code quality, it would be nice if someone could take a quick look and merge this PR.
Thanx!

**Comment by rdmueller** [comment]
PS: feel free to squash it!

**Comment by bodewig** [comment]
I don't really feel competent reviewing powershell code, and you seem to have changed the lineends and moved the file within the same commit. I'm not sure I've caught all the real changes (a newline added, a directory structure change and some changes to the comments are all I've seen).

The groovy code looks fine to me.

**Comment by rdmueller** [comment]
Yeah, I renamed the file because the name had a typo.

I am also not a ps expert, but the code works.

So let's merge it!

**Comment by rdmueller** [comment]
Hm. I forgot to move changes in the manuel to the proper directory. Will do this later this morning

**Pull request merged**
