### PR TITLE
Arc42 help

### PR DESCRIPTION
**Pull request by rdmueller**
Documentation still needs an update

### All Submissions:

* [X] Does your PR affect the documentation?
* [x] If yes, did you update the documentation or create an issue for updating it?

### New Feature Submissions:

1. [ ] Did you create new tests for your submission?
No new tests since this is not too easy to test

2. [x] Does your submission pass all tests? (see travis check)
let's see...

### CODE REVIEW

**Comment by rdmueller** [comment]
issue for updating docs created: https://github.com/docToolchain/docToolchain/issues/119

this PR fixes #117 : It adds preproccessor-statements to be able to turn on and off the rendering of all arc42help sections.

manually tested.

**Comment by jakubjab** [comment]
I think it's a good proposal, but I don't think this should be changed here. I would change that in the https://github.com/arc42/arc42-template repository instead. I'm preparing a PR for #91, which would remove the arc42 template from src/docs and download it from GitHub. Then this change would be lost.

**Comment by rdmueller** [comment]
you are absolutely right. That's why I already created https://github.com/arc42/arc42-template/issues/101, but I didn't have the time yet to fix it the right way.
So let's leave this open until we fix the main issue and then close it without the merge...

**Comment by rdmueller** [comment]
not needed anymore

**Comment by ascheman** [comment]
* Why was it _not needed anymore_, @rdmueller? Due to arc42/arc42-template#101?
* What was your idea to _fix it the right way_, @rdmueller (cf. [this comment](https://github.com/docToolchain/docToolchain/pull/118#issuecomment-345837249))?

**Comment by rdmueller** [comment]
@ascheman I have to say, I don't have a clue anymore.

**Pull request closed without merging**
