### PR TITLE
Gradle 8 compatibility

### LINKED ISSUE #1103: Upgrade to Gradle 8
docToolchain uses Gradle 6.9.2. We have to upgrade Gradle to a version which supports Java 17, a precondition for #1071.

With this issue, we upgrade to the newest release of [Gradle 8](https://gradle.org/whats-new/gradle-8/).

[Deprecation Warnings for an upgrade to Gradle 7](https://scans.gradle.com/s/hran3rnxoehr4/deprecations):
```
➜ ./gradlew help --warning-mode=all

> Configure project :
The testCompile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the testImplementation configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.9.2/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
        at build_7f3j70txdw36gw7pdzvrurdch$_run_closure1.doCall(/home/max/dev/dtc/docToolchain/build.gradle:42)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The testRuntime configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the testRuntimeOnly configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.9.2/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
        at build_7f3j70txdw36gw7pdzvrurdch$_run_closure1.doCall(/home/max/dev/dtc/docToolchain/build.gradle:45)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The AbstractArchiveTask.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the destinationDirectory property instead. See https://docs.gradle.org/6.9.2/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:destinationDir for more details.
        at build_7f3j70txdw36gw7pdzvrurdch$_run_closure5.doCall(/home/max/dev/dtc/docToolchain/build.gradle:176)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

#662 was started but never finished and would be obsolete by this task.

### PR DESCRIPTION
**Pull request by PacoVK**
# Upgrade to Gradle 8

This PR upgrades Gradle to latest 8.1.1 using a workaround based on https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/655 
This allows us to keep up to date with Gradle versions. 

Closes #1103 

**To be discussed**
Do we want to accept the workaround, in order to move forward, or do we want to wait for the official compatibility?

### All Submissions:

* [x] Did you update the `changelog.adoc`?

### CODE REVIEW

**Review by rdmueller — APPROVED** [review]
I am fine with these changes

**Comment by rdmueller** [comment]
if the workaround works, let's use it. seems harmless to me.

**Comment by PacoVK** [comment]
Alright i will merge it soon. I would like to add one of the most important features of Gradle 8, the versionCatalogs which is a real benefit for dependency management

**Comment by mh182** [comment]
A bit late for the merge - nice. Good work

**Pull request merged**
