### PR TITLE
Upgrade Asciidoc Gradle Plugin

### LINKED ISSUE #425: fail on missing images
when asciidoc outputs a warning because of missing image, the build should fail (configurable)

### LINKED ISSUE #517: Use newer version of Asciidoctor Reveal.js
docToolchain uses actually the older version of the RevealJS generator from Asciidoc. Is it possible to upgrade the code to use the new version?

### PR DESCRIPTION
**Pull request by PacoVK**
### Migrate gradle-asciidoc plugin to v3.x

The new plugin comes with loads of improvements. 
This PR also closes #425 and #455 

We could also consider to fail on missing includes in general, but that is open to discuss here 
cc @rdmueller  

Once we conclude this PR is a good one i will take care of the open tasks mentioned below

### All Submissions:

* [x] Did you update the `changelog.adoc`?
* [x] Does your PR affect the documentation?
* [x] If yes, did you update the documentation or create an issue for updating it?

### CODE REVIEW

**Comment by rdmueller** [comment]
wait... did you manage to update the asciidoc gradle plugin in such a short amount of time?

**Comment by PacoVK** [comment]
TBH i spend two evenings mostly because i had to dig really deep into the code of both the plugin and doctoolchain. The good thing was that tests exist 👍  However a good review is essential to ensure i did not miss something although i really tested everything i touched but so far i was not a Gradle expert.

**Comment by mh182** [comment]
Wow. Really good news.
Upgrading the Gradle Asciidoc plugin was a major blocker for a lot of other tickets. Especially support for java 17 (#1071 ).

If this is integrated we should test for upgrades to Java 17.

**Comment by PacoVK** [comment]
Alright, seems like this is something that is definitely needed, then i will go through the docs and update it accordingly as well as the outstanding changelog :)

**Comment by PacoVK** [comment]
i am pretty sure there could also be some code clean-up and seems we do not need to checkout revealJS anymore as well as the gems. I need some help in order to not delete soemthing that is still important but the latest plugins seems to be a pretty comprehensive one in that regard. 
Now that i finished the last "legacy" part i will get the docs part and create a changelog entry soon

**Comment by PacoVK** [comment]
I changed the title of the PR since this PR actually got a broader scope. 
still pending some more documentation, especially i'd like to add some more for the `generateDeck` task since it is really bare-bones yet

**Review by mh182 — APPROVED** [review]
I'm impressed. Thanks for the good work. 

I made a minor change to the changelog to emphasize the removal of the clone scripts, which were just there to clone the reveal.js repository.

**Comment by mh182** [comment]
> i am pretty sure there could also be some code clean-up and seems we do not need to checkout revealJS anymore as well as the gems. I need some help in order to not delete soemthing that is still important but the latest plugins seems to be a pretty comprehensive one in that regard.

We currently have a PR with a complete rewrite of `dtcw`. Depending on which PR we are going to merge first, we have to resolve the cleanup again.

Apart from the documentation, is there anything else missing before we can integrate your change?

**Comment by mh182** [comment]
Question: is #1061 still reproducible? If not, we will mark it as fixed with your PR.

**Comment by PacoVK** [comment]
> Question: is #1061 still reproducible? If not, we will mark it as fixed with your PR.

Just tested, seems like this PR also resolves #1061 all tests passed

**Comment by PacoVK** [comment]
@mh182  thanks really appreciate your feedback here. I think i'm done so far, just added small docs improvements for generateDeck task, to ease customization of RevealJs decks. 

I just recognized the `dtcw` rewrite PR, i think a cleanup might be more suitable there to limit the scope of this very PR here. Depending on the amount of changes it could be even worth to consider to have them in a separate PR after merging both, this and #1077 to even keep the scope there limited as well. 

What do you think?

**Comment by mh182** [comment]
@PacoVK I agree. I think we should integrate this PR. I will make the cleanup in the `dtcw` PR afterward.

So I will merge your changes into `ng`.

I tried to go through older open issues which will be solved by this PR. But since I'm not that deep in this area, I could not decide if they are fixed by this PR.   

Could you do e a favor and skim over existing issues and mark them as closed in case our PR fixes them?

**Comment by PacoVK** [comment]
@mh182 i can do that ofc, what do you mean with mark as closed? Put a comment and mention you? I have no rights to close PRs in the main repo 🙋‍♂️

**Pull request merged**
