### PR TITLE
exportEAP.vbs small improvements

### PR DESCRIPTION
**Pull request by Zheng-Bote**
### All Submissions:

* [x] Did you update the `changelog.adoc`?
* [ ] Does your PR affect the documentation?
* [ ] If yes, did you update the documentation or create an issue for updating it?

The source of the documentation can be found in `/src/docs/`.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Your first submission

* [ ] Welcome to the list of contributors! If you have any questions, feel free to ask them by creating a new issue
* [x] Have you added your name to the list of [30_community.adoc](https://github.com/docToolchain/docToolchain/blob/ng/src/docs/10_about/30_community.adoc)?

inspiration: https://github.com/stevemao/github-issue-templates

### CODE REVIEW

**Comment by rdmueller** [comment]
thanx! I don't see a new entry in the changelog - could you do me a favour and add one?

**Comment by Zheng-Bote** [comment]
Ups *o*, of course will do so

Ralf D. Müller ***@***.***> schrieb am So., 12. Feb. 2023,
22:12:

**Comment by Zheng-Bote** [comment]
updated changelog.adoc as well as 30_community.adoc (proud to be part of this project)

**Comment by rdmueller** [comment]
thanx! Glad to have you on board!

**Pull request merged**
