### PR TITLE
Fix for #259 and issues with standalone doctoolchain

### PR DESCRIPTION
**Pull request by jakubjab**
After this change, to generate docToolchain manual you need to specify inputPath and optionally pdfThemeDir:

./gradlew -PinputPath=./src/docs generateHTML
./gradlew -PinputPath=./src/docs -PpdfThemeDir=./src/docs/pdfTheme generatePDF

@rdmueller - please check if that doesn't break some of your assumptions/rules.

### CODE REVIEW

**Comment by rdmueller** [comment]
Thanx for this contribution! More step further to make the interface more stable...

so, it does break something :-) I need some time to check if it is just the tests or more...
So please be patient...

**Comment by jakubjab** [comment]
The tests were breaking for me even without this change, on plaim master. I should have fixed them before the change.

About the generation of the manual - maybe I would just document how to generate it using bin/doctoolchain (and copy to the right place) in the manual itself, and not strive to make this use case the simplest one.

**Comment by rdmueller** [comment]
hm. the tests where working for travis. So it seems that you environment is different to the test environment.

I will check this.

Regarding the manual: there is this [copyDocs.sh](https://github.com/docToolchain/docToolchain/blob/master/copyDocs.sh) script which could be extended to generate & copy. I will take a look at this.

**Comment by rdmueller** [comment]
I currently try to find out what is going on. The `exportExcel`- Task seems to export into the root folder.
I guess your tests where green because you already had those exported files in your `src/docs` folder and this only happens with a clean clone...

I now try to get some debug output but somehow it does not appear in the test report...

**Comment by rdmueller** [comment]
So, the problem seems to lie in this line:
https://github.com/docToolchain/docToolchain/blob/master/scripts/AsciiDocBasics.gradle#L42

`srcDir  = "${docDir}/${inputPath}"`

you change sets `docDir` and ìnputPath` both to `.` but the tests expect that `docDir` is the path to the documentation project and `inputPath` is the path to the input files (`src/docs`)

I wonder how we can fix this. I will first try to fix the `exportExel` tests..

**Comment by rdmueller** [comment]
Hi Jakub, sorry, it took me quite a long time to get back to this PR.

I've just upgraded the gradle version and fixed three tests (the ones which are failing with this PR).
Could you try to do a rebase on your branch so taht your change are on top of the master branch?

thanx, Ralf

**Comment by jakubjab** [comment]
@rdmueller - after merge from master the tests are passing. However, I'm not sure what other things may fail. Can we have at least a list of manual tests to perform before merge? Then we could gradually make them automatic.

**Comment by rdmueller** [comment]
hm. reagarding the manual tests - I would like to invest in some automated tests. So tell me about manual tests you do and I try to automate them.

but as for now, I guess you can easily test if your use cases still work and I will test mine.

If we are both happy, I am fine with merging this PR...

**Comment by rdmueller** [comment]
... and if we find additional bugs, let's first write a test before fixing them...

**Comment by rdmueller** [comment]
ok. my build breaks because of the input path.
old version: src/docs
this version: .

this results in `generateHTML` not finding the input files.

but I think I have a fix...

**Comment by rdmueller** [comment]
argh. that broke lot of tests.
I think we need a better concept for  the configuration.

I think it would be great to have all configs in one file, independent of the gradle.properties file.
What do you think?

**Comment by rdmueller** [comment]
next fix - now only three test break

**Comment by jakubjab** [comment]
The latest version works for me, but I only use generateHTML and generatePDF. The tests are failing for me locally as well. I can try fixing them.

Regarding the configuration - I would be happiest if we could avoid configuration files at all, and pass all information in the command line. In gradle world this would be with -P I guess. Then it's flexible and different users can wrap it as they wish.

**Comment by rdmueller** [comment]
regardings the config, let's start small.
I've created an issue for that: https://github.com/docToolchain/docToolchain/issues/310

**Comment by jakubjab** [comment]
I have fixed the failing test cases. Seems that with the current version it's not possible to override the inputPath from the command line. But this could be the next step, once we agree on #310.

This version works for me as a standalone tool and fixes #259.
@rdmueller and everyone else interested - please check if your use cases are still working as expected with this change. If yes, then I think we could merge it.

**Comment by rdmueller** [comment]
very cool, thanx! I will test it tomorrow...

**Comment by rdmueller** [comment]
tests are green and changes look ok to me, so I will now sqash an merge.
Thanx for this fix!

**Pull request merged**
