### PR TITLE
Feature/export jira to excel

### PR DESCRIPTION
**Pull request by ewoks**
PR regarding https://github.com/docToolchain/docToolchain/issues/454

- Support for multiple Jira queries
- Basic support for custom fields in Jira results
- Saving to Excel files

### All Submissions:

* [x] Does your PR affect the documentation?
* [x] If yes, did you update the documentation or create an issue for updating it?

The source of the documentation can be found in `/src/docs/manual`.
To "publish" it, execute `./gradlew exportContributors && ./gradlew && ./copyDocs.sh`.
This will convert the `.adoc` file to HTML and copy them to the right folder so that github pages will pick them up.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Change to Documentation:

* [x] Did you build the docs and copy them to the `/docs` folder?
* [x] If not, did you create an issue for doing so?

inspiration: https://github.com/stevemao/github-issue-templates

### CODE REVIEW

**Comment by ewoks** [comment]
Added ticket for documentation update

**Comment by ewoks** [comment]
@rdmueller do you have some suggestions on this?

**Comment by rdmueller** [comment]
the feature sounds great.
Do I understand the code in the right way that it is a breaking change? So if users used the old feature, they will have to update their config?

**Comment by ewoks** [comment]
That's correct. Old configuration is incompatible. Can you suggest how we cause the least pain for the users?
Migration is pretty simple, as I added comments at the bottom of the Config.groovy but not sure about the best way to call users attention to it. Documentation with snippet of new configuration?

**Comment by rdmueller** [comment]
the code could check if the `requests`-map is empty and if so, it could populate it from the old `jql`-config. What do you think?

**Comment by ewoks** [comment]
Sounds like a good transition solution. I will try to work on it in the following days and ping you when it is ready. 
I would still emphasize that this is legacy configuration that would be removed in the future. Is that ok?

**Comment by rdmueller** [comment]
> I would still emphasize that this is legacy configuration that would be removed in the future. Is that ok?

yes, let's mark it as depracated and output a warning. But I think we should support it for 6-12 month

**Comment by rdmueller** [comment]
looks good to me. thanx for your work!

**Pull request merged**
