### PR TITLE
1045 dtcw without help

### LINKED ISSUE #1045: Calling the wrapper script without any argument does not provide helpful output
This is a regression already reported in #1043.

Calling the wrapper script without any argument does not provide helpful output. The the wrapper script of version v2.1.0 provided a good description what the user should do next. 

**To Reproduce**
1. Install the wrapper script
```
~/tmp 
➜ mkdir test && cd test

~/tmp/test 
➜ curl -sLo dtcw doctoolchain.github.io/dtcw

~/tmp/test 
➜ chmod +x dtcw 
```
2. Call the wrapper script with no arguments
```
~/tmp/test 
➜ ./dtcw

dtcw - docToolchain wrapper V0.36
docToolchain V2.2.0
docToolchain as CLI available
No valid argument(s) supplied
```

**Expected behavior**
The user is provided with helpful information what they should do next. In previous releases we had following output.
```
./dtcw 

dtcw - docToolchain wrapper V0.36
docToolchain V2.1.0
docToolchain as CLI available
local java JDK found
use /home/max/.doctoolchain/jdk as JDK

Usage: ./dtcw [option...] [task...]

You can use the same options and tasks as in underlying gradle.
Use "./dtcw tasks --group doctoolchain" to see available tasks.
Use "local", "sdk" or "docker" as first argument to force the use of a local, sdkman or docker install.

Examples:

  Download and install arc42 Template:
    ./dtcw downloadTemplate

  Generate PDF:
    ./dtcw generatePDF

  Generate HTML:
    ./dtcw generateHTML

  Publish HTML to Confluence:
    ./dtcw publishToConfluence

  get more documentation at https://doctoolchain.github.io
```

**Screenshots**

**Configuration**
 - docToolchain version: v2.20
 - OS: Linux
 - Relevant SDK Versions: the one provided with `getJava`

### PR DESCRIPTION
**Pull request by rdmueller**
this should fix the issue.

### CODE REVIEW

**Comment by rdmueller** [comment]
@mh182 since you are currently so active helping - would you like to review my change before we merge it?

**Review by mh182 — APPROVED** [review]
Looks good to me.

**Comment by mh182** [comment]
I"m not used to work/cooperate on github. I rebased and merged the PR. But the commit doesn't contain a reference to the original ticket number.
It is not a good practice to integrate commits which don't reference to any ticket number.

**Comment by rdmueller** [comment]
I opened the new branch from within the issue. This auto-generates a branch name which starts with the issue number. This seems to be enough reference for github. But to be honest, I also switched to this workflow only aproc 10 issues ago. So let's see how this works...

**Comment by rdmueller** [comment]
Bte: I also try to squash commits and use conventional commit messages for the PR in order to try to keep the history cleaner. But this is only on a best effort basis and also just since two weeks 😁

**Comment by mh182** [comment]
The github interface didn't provide me a rabes+squash option (what I was searching for). 
I would prefer you are merging the issues until I get more used to the HG workflow here.

**Pull request merged**
