### PR TITLE
Update asciidoc diagram (plantUML) dependency version

### LINKED ISSUE #526: Old PlantUML provides rendering issues
**Describe the bug**
Some of our graphics have issues while getting rendered because the PlantUML version is quite old.

**To Reproduce**
Add the following chart to your asciidoc file.

`[plantuml,"ci-cd-plantuml",png]
----
@startuml
skinparam linetype ortho

node "Local" {
[IDE] -down-> gitops : commit configuration
[IDE] -down-> service_source : commit application
service_source -right-> gitops : update version
}

cloud "AWS" {
    [AWS CodeCommit] ->  [AWS Lambda] : triggering
    [AWS Lambda] -> [ArgoCD] : triggering
    [ArgoCD] -down-> [AWS CodeCommit] : pulls

    cloud "AWS EKS" as eks {
        [ArgoCD] -> [HELM registry] : configuration
        [ArgoCD] -> [Service ...] : deploy
        [AWS ECR] -down-> [Service ...] : provides docker image

    }
}

node "Git" {
artifact "git" {
    folder "xxx"{
        xxx -down-> [AWS CodeCommit] : provide configuration to
    }
    folder "service_source"{
        service_source -> gitlab_runner : build
    }

    node "gitlab_runner"{
        gitlab_runner -down-> [AWS ECR] : package
    }
}
}

@enduml
----`

**Expected behavior**
Chart is rendered correctly

**Screenshots**
image

**Configuration**
 - docker container, v1.2, v1.3

### PR DESCRIPTION
**Pull request by DaHoC**
Update asciidoc pdf and diagram (plantUML) dependency versions to fix #526

### All Submissions:

* [ ] Does your PR affect the documentation?
* [ ] If yes, did you update the documentation or create an issue for updating it?

The source of the documentation can be found in `/src/docs/manual`.
To "publish" it, execute `./gradlew exportContributors && ./gradlew && ./copyDocs.sh`.
This will convert the `.adoc` file to HTML and copy them to the right folder so that github pages will pick them up.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Your first submission

* [ ] Welcome to the list of contributors! If you have any questions, feel free to ask them by creating a new issue
* [x] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?

### New Feature Submissions:

1. [ ] Did you create new tests for your submission?
2. [ ] Does your submission pass all tests? (see travis check)

### Changes to Core Features:

* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### Change to Documentation:

* [ ] Did you build the docs and copy them to the `/docs` folder?
* [ ] If not, did you create an issue for doing so?

inspiration: https://github.com/stevemao/github-issue-templates

### CODE REVIEW

**Comment by rdmueller** [comment]
perfect - thank you!
Have you added your name to the list of contributors.adoc?

**Comment by rdmueller** [comment]
perfect! :-) Welcome... and thanx for the PR!

**Comment by DaHoC** [comment]
You are welcome, thank you for merging so quickly!
On a side-node: In our projects we successfully use automated dependency-checking, i.e. [Dependabot](https://dependabot.com/).

**Comment by rdmueller** [comment]
Feel free to suggest any enhancements - I am happy when the community takes over :-)

**Pull request merged**
