### PR TITLE
Update of asciidoctorj-pdf to latest release version 1.5.3

### PR DESCRIPTION
**Pull request by stehlih**
* [N] Does your PR affect the documentation?
* [] If yes, did you update the documentation or create an issue for updating it?

Update of :asciidoctorj-pdf to latest release version 1.5.3 (Issue #411) by using solution of Barney-42.

To generate PDFs with many images the generatePDF task requires much more memory.
I've tested it with some of our largest documents and with 2GB xmx it works without OutOfMemory exceptions on Windows and in a Linux Docker container.

### CODE REVIEW

**Comment by rdmueller** [comment]
thanx for the PR!

Wow - there are more changesets than changes and the tests fail.
Have you already analyzed why the tests fail?

**Comment by stehlih** [comment]
asciidoctorj-pdf:1.5.3 requires asciidoctorj 1.6.2 and in asciidoctorj 1.6.0 the method createInline was renamed to createPhraseNode.

**Comment by rdmueller** [comment]
thank you very much. I will squash your commits into one single commit....

**Comment by rdmueller** [comment]
sorry, for the revert back and forth - I tried to squash your commits, didn't succeed and thought I could revert the last PR in order to squash it again. But again, I didn't succeed and reverted my last revert :-(

I guess I have to learn more about these mechanisms...

**Pull request merged**
