### PR TITLE
Improve confluence export performance

### PR DESCRIPTION
**Pull request by Hellmy**
### All Submissions:

* [x] Did you update the `changelog.adoc`?
* [x] Does your PR affect the documentation?
* [x] If yes, did you update the documentation or create an issue for updating it? I've edited the config documentation

### Problem

Current implementation always scans the whole confluence space what takes quite long if the space has many pages (have seen about 8 minutes only scanning...)

### Proposal

When the confluence configuration has only ancestorIds given. Only the given pages' childs and the grandchild and so on are scanned.

### Notes

I thought to have seen a discussion about this but haven't found it so just a pull request for now - any other one remembers?

A merge ot the master would be helpful as there I've alreade added the mavenUsername and mavenPassword

### CODE REVIEW

**Comment by rdmueller** [comment]
wow. thanx for adding tests.

**Comment by Hellmy** [comment]
Could you restart the checks or how to do that - i think the checks should now resolve as the master is already in the ng branch...

**Comment by rdmueller** [comment]
@Hellmy sorry, some thing take too long for me to verify.
I managed to re-run the checks. I don't care about the netlify checks, but it seems that your newly generated tests fail:

```
docToolchain.export2confluence.Export2ConfluenceSpec > test space output FAILED
    groovy.lang.MissingMethodException: No signature of method: static java.util.Map.of() is applicable for argument types: () values: []
    Possible solutions: is(java.lang.Object), any(), sort(), sort(groovy.lang.Closure), max(groovy.lang.Closure), any(groovy.lang.Closure)
        at docToolchain.export2confluence.Export2ConfluenceSpec.test space output(Export2ConfluenceSpec.groovy:23)

docToolchain.export2confluence.Export2ConfluenceSpec > test ancestor-id output FAILED
    groovy.lang.MissingMethodException: No signature of method: static java.util.Map.of() is applicable for argument types: () values: []
    Possible solutions: is(java.lang.Object), any(), sort(), sort(groovy.lang.Closure), max(groovy.lang.Closure), any(groovy.lang.Closure)
        at docToolchain.export2confluence.Export2ConfluenceSpec.test ancestor-id output(Export2ConfluenceSpec.groovy:54)
```

Do you see what's wrong?

**Comment by Hellmy** [comment]
> Export2ConfluenceSpec

Map initialisation has another style in java 8 than in java 11+...
Not quite sure, if I now got all changes right after there were some conflicts during update but probably you have them still in mind as there was a change with the limits for retrieving the pages!?

**Comment by rdmueller** [comment]
thanx for the fix. without further testing, I now merge this code for the next release.

**Comment by rdmueller** [comment]
regarding the master branch... I would merge it if you send a PR :-)

**Comment by Hellmy** [comment]
> regarding the master branch... I would merge it if you send a PR :-)

The master is already merged into the ng - dunno when and where but good job =)
Thanks for the work and fast response

**Comment by rdmueller** [comment]
ah! ok, I tthought you referenced the other way around, that you would like to use this functionality with the old 1.3.x branch. thanx for the feedback

**Pull request merged**
