### PR TITLE
add suggested suffix to docker container to prevent name conflicts

### LINKED ISSUE #829: Multiple run of dtcw with docker is failing because of a container name conflict
**Describe the bug**
Multiple run of docToolchain via docker is not supported on the same machine

**To Reproduce**
Have long run of docToolchain and start 2 of them in parallel.

**Current behavior**

Failing with:
```
./dtcw generateSite
dtcw - docToolchain wrapper V0.29
docToolchain V2.0.3
docker available
/usr/bin/docker
use docker installation
docker: Error response from daemon: Conflict. The container name "/doctoolchain" is already in use by container "3352c81b6369435e454b2343e3862cb5d14c151fad635322ec9b505909065270". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

**Expected behavior**
Is it really required to name the container to a fix name, couldn't be something like "doctoolchain+<currentTimeMillis>" or something random.

**Configuration**
 - docToolchain 2.0.3
 - OS: Linux

### PR DESCRIPTION
**Pull request by PacoVK**
Fixes #829 

### All Submissions:

* [x] Did you update the `changelog.adoc`?

### CODE REVIEW

**Review by mh182 — APPROVED** [review]

**Comment by mh182** [comment]
Could you rebase this commit and squash it in one commit?

**Comment by PacoVK** [comment]
@mh182 i am just failing to fix the tests :/ also the powershell is missing. If i rebase, would you take over?

**Comment by mh182** [comment]
I can take over. But I have no idea if I can push my changes to your repo. 
Let's try.

**Comment by PacoVK** [comment]
This PR is so small and the changes were already in the ticket, just create a new one and we close this PR as duplicate 👍

**Comment by mh182** [comment]
I created a new PR #1143, so closing this one since duplicate.

**Pull request closed without merging**
