### PR TITLE
Docsedit - Minor changes to 3 Tasks docs (Jody)

### PR DESCRIPTION
**Pull request by JodyWinter**
### All Submissions:

* [ ] Did you update the `changelog.adoc`?
* [X] Does your PR affect the documentation?
* [X] If yes, did you update the documentation or create an issue for updating it?

The source of the documentation can be found in `/src/docs/`.

If you didn't find the time to update docs, please create an issue as reminder to do so.

### Your first submission

* [ ] Welcome to the list of contributors! If you have any questions, feel free to ask them by creating a new issue
* [ ] Have you added your name to the list of [contributors.adoc](https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual/05_contributors.adoc)?

inspiration: https://github.com/stevemao/github-issue-templates

### CODE REVIEW

**Comment by rdmueller** [comment]
Thanx. This PR worked great.
I changed the formatting a bit in order to adhere to the "one sentence / thought per line rule"

**Comment by JodyWinter** [comment]
I haven't come across that rule yet. I always write in paragraphs as it flows better when reading. I think that one line per thought looks disjointed and a bit old-fashioned. Over to you, but maybe think about moving to a run-on paragraph style?

**Comment by rdmueller** [comment]
the main reason behind this rule is that you get better diffs in github - this way you can easily see what has been changed, because git manages to higlight it for you.

https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line

**Comment by JodyWinter** [comment]
But on your website pages, don't you want 'normal' writing/paragraphs? Sorry - I'm not sure I fully understand.

**Pull request merged**
