### PR TITLE
Write a Tutorial on how to change the Theme for a Microsite #1153

### LINKED ISSUE #1153: Write a Tutorial on how to change the Theme for a Microsite

### PR DESCRIPTION
**Pull request by rdmueller**

### CODE REVIEW

**Comment by rdmueller** [comment]
Hi @JodyWinter, we've written a small tutorial, but I fear our english can be brushed up. Would be great if you could add your review :-)

**Comment by JodyWinter** [comment]
Hi @rdmueller! Sorry this has taken me so long! I did the review and edited the file. Can you take a look to see if I committed it correctly?

**Comment by rdmueller** [comment]
Hi @JodyWinter,

> Can you take a look to see if I committed it correctly?

yes, seems that everything worked perfect. Let's merge it!

**Comment by rdmueller** [comment]
@JodyWinter somehow it didn't recognize your edit as "review". Let's merge anyway...

**Pull request merged**
