### PR TITLE
dtcw: install java 17

### LINKED ISSUE #1129: `dtcw install java` installs Java 17
Let's make Java 17 the default major version.

**Describe the solution you'd like**
`./dtcw install java` installs Java 17.

Check and update the documentation in case we use older Java versions.

### PR DESCRIPTION
**Pull request by mh182**
Closes #1129

### CODE REVIEW

**Comment by mh182** [comment]
Hmm, the deployment on Netlify breaks since we use docToolchain 2.2.1. 

Should we not use the `latest` version when we deploy the page?

**Comment by rdmueller** [comment]
yes, I guess latest makes sense... I will switch this in a moment

**Comment by rdmueller** [comment]
the script tried to switch the version to "dev". I have just fixed the expressions. let's see if the preview now deploys

**Review by rdmueller — APPROVED** [review]
looks good to me!

**Review by PacoVK — APPROVED** [review]

**Pull request merged**
